baseURL = 'http://example.org/'
languageCode = 'ja-jp'
title = 'オルタナティブ人形劇団「劇団☆死期」 HP'
theme = 'ananke'
description = '2010年夏、現代美術家の掛声で、超実験的特殊人形劇団「劇団☆死期」が始動しました。「劇団☆死期」とは、極めて実験性の高い人形劇団です。劇団☆死期」とは、「劇団☆死期」としての人形劇、である事以外には表現のスタイルは設けません。'
